import type { AnalysisResult } from "@/lib/api/types";
import { CheckCircle2, FileText, Sparkles, XCircle } from "lucide-react";

interface AiReferenceSectionProps {
  aiResult: AnalysisResult | null | undefined;
  extractedSkills?: string[] | null;
}

export function AiReferenceSection({
  aiResult,
  extractedSkills,
}: AiReferenceSectionProps) {
  const matchPercentage = aiResult?.matchPercentage ?? null;
  const matchedSkills = aiResult?.matchedSkills ?? [];
  const missingSkills = aiResult?.missingSkills ?? [];

  return (
    <section className="rounded-xl border border-zinc-200 bg-white p-6 shadow-xs dark:border-zinc-800 dark:bg-zinc-900">
      {/* Section Header */}
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <div className="rounded-lg bg-indigo-50 p-2 text-indigo-600 dark:bg-indigo-950/60 dark:text-indigo-400">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-base font-bold tracking-tight text-zinc-900 dark:text-zinc-100 sm:text-lg">
              AI Generated Result
            </h2>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Read-only baseline analysis generated by the AI evaluation model.
            </p>
          </div>
        </div>

        <span className="self-start rounded-full border border-indigo-200 bg-indigo-50 px-2.5 py-0.5 text-xs font-semibold text-indigo-700 dark:border-indigo-900/50 dark:bg-indigo-950/50 dark:text-indigo-300 sm:self-auto">
          Read-Only Reference
        </span>
      </div>

      {/* Match Score Display */}
      <div className="mt-5 grid gap-4 sm:grid-cols-3">
        <div className="rounded-lg border border-zinc-200/80 bg-zinc-50/60 p-4 dark:border-zinc-800 dark:bg-zinc-950/40">
          <p className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
            AI Match Percentage
          </p>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="font-mono text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
              {matchPercentage !== null
                ? `${matchPercentage.toFixed(2)}%`
                : "—"}
            </span>
          </div>
          {matchPercentage !== null && (
            <div className="mt-3 h-2 w-full overflow-hidden rounded-full bg-zinc-200 dark:bg-zinc-800">
              <div
                className={`h-full rounded-full transition-all ${
                  matchPercentage >= 70
                    ? "bg-emerald-500"
                    : matchPercentage >= 40
                      ? "bg-amber-500"
                      : "bg-red-500"
                }`}
                style={{
                  width: `${Math.min(100, Math.max(0, matchPercentage))}%`,
                }}
              />
            </div>
          )}
        </div>

        <div className="rounded-lg border border-emerald-200/70 bg-emerald-50/40 p-4 dark:border-emerald-950/60 dark:bg-emerald-950/20">
          <p className="text-xs font-medium text-emerald-800 dark:text-emerald-300">
            AI Matched Skills
          </p>
          <p className="mt-2 font-mono text-3xl font-bold tracking-tight text-emerald-900 dark:text-emerald-200">
            {matchedSkills.length}
          </p>
          <p className="mt-1 text-[11px] text-emerald-700/80 dark:text-emerald-400">
            Skills identified in resume matching career profile
          </p>
        </div>

        <div className="rounded-lg border border-rose-200/70 bg-rose-50/40 p-4 dark:border-rose-950/60 dark:bg-rose-950/20">
          <p className="text-xs font-medium text-rose-800 dark:text-rose-300">
            AI Missing Skills
          </p>
          <p className="mt-2 font-mono text-3xl font-bold tracking-tight text-rose-900 dark:text-rose-200">
            {missingSkills.length}
          </p>
          <p className="mt-1 text-[11px] text-rose-700/80 dark:text-rose-400">
            Skills required by career but not found in resume
          </p>
        </div>
      </div>

      {/* Skills Lists Grid */}
      <div className="mt-6 grid gap-6 md:grid-cols-2">
        {/* Matched Skills */}
        <div className="space-y-2.5">
          <h3 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">
            <CheckCircle2 className="h-4 w-4" />
            Matched Skills ({matchedSkills.length})
          </h3>
          {matchedSkills.length === 0 ? (
            <p className="text-xs italic text-zinc-400">
              No matched skills identified by AI.
            </p>
          ) : (
            <div className="flex flex-wrap gap-1.5">
              {matchedSkills.map((skill, index) => (
                <span
                  key={`${skill}-${index}`}
                  className="inline-flex items-center gap-1 rounded-md border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/40 dark:text-emerald-300"
                >
                  <CheckCircle2 className="h-3 w-3 shrink-0 text-emerald-600 dark:text-emerald-400" />
                  {skill}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Missing Skills */}
        <div className="space-y-2.5">
          <h3 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-rose-700 dark:text-rose-400">
            <XCircle className="h-4 w-4" />
            Missing Skills ({missingSkills.length})
          </h3>
          {missingSkills.length === 0 ? (
            <p className="text-xs italic text-zinc-400">
              No missing skills identified by AI.
            </p>
          ) : (
            <div className="flex flex-wrap gap-1.5">
              {missingSkills.map((skill, index) => (
                <span
                  key={`${skill}-${index}`}
                  className="inline-flex items-center gap-1 rounded-md border border-rose-200 bg-rose-50 px-2.5 py-1 text-xs font-medium text-rose-800 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-300"
                >
                  <XCircle className="h-3 w-3 shrink-0 text-rose-600 dark:text-rose-400" />
                  {skill}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Extracted Skills (if present) */}
      {extractedSkills && extractedSkills.length > 0 && (
        <div className="mt-6 border-t border-zinc-100 pt-5 dark:border-zinc-800">
          <h3 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-zinc-600 dark:text-zinc-400">
            <FileText className="h-4 w-4" />
            Extracted Skills from Candidate Resume ({extractedSkills.length})
          </h3>
          <div className="mt-2.5 flex flex-wrap gap-1.5">
            {extractedSkills.map((skill, index) => (
              <span
                key={`${skill}-${index}`}
                className="inline-flex items-center rounded-md border border-zinc-200 bg-zinc-100 px-2.5 py-1 text-xs text-zinc-700 dark:border-zinc-800 dark:bg-zinc-800 dark:text-zinc-300"
              >
                {skill}
              </span>
            ))}
          </div>
        </div>
      )}
    </section>
  );
}
